In [3]:
import numpy as np

In [8]:
#Create a numpy array of size 10, filled with zeros
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
#Create a numpy array with values ranging from 10 to 49 and set its datatype to float
arr1 = np.array(range(10,49),dtype=float)
arr1

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.])

In [16]:
#Create a numpy matrix of 2*2 integers, filled with ones.
arr2 = np.ones((2,2))
arr2

array([[1., 1.],
       [1., 1.]])

In [17]:
#Create a numpy matrix of 3*2 float numbers, filled with ones.
arr3 = np.ones((3,2),dtype=float)
arr3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
#Given the X numpy array, create a new numpy array with the same shape and type as X,filled with ones. (
#hint: search the function np.ones_like( )
X = np.array([1,2,3,4,5,6])
new_X = np.ones_like(X)
new_X

array([1, 1, 1, 1, 1, 1])

In [27]:
#Given the X numpy matrix, create a new numpy matrix with the same shape and type as
#X, filled with zeros. (hint: similar function as above exists for zeros as well)
X = np.array([[1,2,3,4],[5,6,7,8]])
new_X = np.zeros_like(X)
new_X

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [31]:
#Create a numpy matrix of 4*4 integers, filled with fives.
X = np.full((4,4),5)
X

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [35]:
#Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
X = np.array([[1,2],[2,2]])
new_X = np.full_like(X,7)
new_X

array([[7, 7],
       [7, 7]])

In [38]:
#Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
#10. Create a numpy array, filled with 3 random integer values between 1 and 10.
x = np.random.randint(1,11,3)
x

array([8, 7, 9])

In [46]:
#11. Create a 3*3*3 numpy matrix, filled with random float values.
x = np.random.rand(3,3,3)
x

array([[[0.75394536, 0.71418266, 0.25615213],
        [0.47778595, 0.69368285, 0.12353687],
        [0.63980304, 0.93626148, 0.10739141]],

       [[0.9862621 , 0.10697961, 0.32826106],
        [0.85331222, 0.67893272, 0.79233833],
        [0.75400149, 0.77001201, 0.26822933]],

       [[0.15222395, 0.02489614, 0.36275345],
        [0.60592659, 0.3511687 , 0.89941744],
        [0.25694218, 0.52253094, 0.04415008]]])

In [61]:
#12. Create a numpy array with numbers from 1 to 10
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
#13. Create a numpy array with the odd numbers between 1 to 10
x = np.arange(1,10,step=2)
x

array([1, 3, 5, 7, 9])

In [55]:
#14. Create a numpy array with numbers from 1 to 10, in descending order.
x = np.arange(10,0,-1)
x



array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [65]:
#15. Create a 3*3 numpy matrix, filled with values ranging from 0 to 8
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
#Given the X numpy array, show its first element
X = np.array(['A','B','C','D','E'])
X[0]



'A'

In [69]:
#Given the X numpy array, show its last element
X = np.array(['A','B','C','D','E'])
X[4]

'E'

In [71]:
#Given the X numpy array, show its first three elements
X = np.array(['A','B','C','D','E'])
X[:3]

array(['A', 'B', 'C'], dtype='<U1')

In [73]:
#Given the X numpy array, show all middle elements
X = np.array(['A','B','C','D','E'])
X[1:4]

array(['B', 'C', 'D'], dtype='<U1')

In [77]:
#Given the X numpy array, show the elements in reverse position.
X = np.array(['A','B','C','D','E'])
X_new=np.flip(X)
X_new
#X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [78]:
#Given the X numpy array, show the elements in an odd position.
X = np.array(['A','B','C','D','E'])
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [81]:
#Given the X numpy matrix, show the first row’s elements.
X = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X[0]

array([1, 2, 3, 4])

In [82]:
#8. Given the X numpy matrix, show the last row elements.
X = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X[3]

array([13, 14, 15, 16])

In [83]:
#9. Given the X numpy matrix, show the first element on first row
X = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X[0][0]

1

In [84]:
#Given the X numpy matrix, show the last element on last row.
X = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X[3][3]

16

In [86]:
#11. Given the X numpy matrix, show the first two elements on the first two rows.
X = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X[:2][:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [99]:
#12. Given the X numpy matrix, show the last two elements on the last two rows
X = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X[-2:,-2:]

array([[11, 12],
       [15, 16]])

In [104]:
#1. Convert the given integer numpy array to float (you need to google the function that will help you do this)
X = [-5, -3, 0, 10, 40]
X = np.array(X)
new_x=X.astype(float)
new_x

array([-5., -3.,  0., 10., 40.])

In [105]:
#Reverse the given numpy array (first element becomes last) through indexing
X = [-5, -3, 0, 10, 40]
X[::-1]

[40, 10, 0, -3, -5]

In [108]:
#Given the X numpy array, set the fifth element equal to 1
X = np.zeros(10)
X[4]=1
X
#X[-1,:]=1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [112]:
#4. Given the X numpy matrix, change the last row with all 1
X = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X[3]=[1]
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [120]:
#5. Given the X numpy matrix, add 5 to every element
X = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]
])
X=X+5
X

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])